"""init tables

Revision ID: 130d51c9840d
Revises: 3acf1625cd82
Create Date: 2025-10-13 14:14:08.260337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '130d51c9840d'
down_revision: Union[str, Sequence[str], None] = '3acf1625cd82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('learning_objectives', sa.Text(), nullable=True),
    sa.Column('learning_plan_links', sa.Text(), nullable=True),
    sa.Column('learning_materials', sa.Text(), nullable=True),
    sa.Column('pass_percentage', sa.Float(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_id', 'level_name', name='uq_training_level_name'),
    sa.UniqueConstraint('training_id', 'level_order', name='uq_training_level_order')
    )
    op.create_index(op.f('ix_training_levels_id'), 'training_levels', ['id'], unique=False)
    op.create_table('mcq_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_level_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.String(), nullable=False),
    sa.Column('option_b', sa.String(), nullable=False),
    sa.Column('option_c', sa.String(), nullable=False),
    sa.Column('option_d', sa.String(), nullable=False),
    sa.Column('correct_option', sa.Enum('A', 'B', 'C', 'D', name='mcq_option'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['training_level_id'], ['training_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcq_questions_id'), 'mcq_questions', ['id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('training_level_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('evaluation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('mcq_score', sa.Float(), nullable=True),
    sa.Column('practical_score', sa.Float(), nullable=True),
    sa.Column('assignment_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('max_possible_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'passed', 'failed', name='evaluationstatus'), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('evaluated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['evaluated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['training_level_id'], ['training_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    op.create_table('mcq_exam_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('training_level_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('questions_attempted', sa.Integer(), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('percentage_score', sa.Float(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'passed', 'failed', name='exam_status'), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['training_level_id'], ['training_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcq_exam_attempts_id'), 'mcq_exam_attempts', ['id'], unique=False)
    op.create_table('training_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('week_start_date', sa.DateTime(), nullable=False),
    sa.Column('week_end_date', sa.DateTime(), nullable=False),
    sa.Column('hours_completed', sa.Float(), nullable=True),
    sa.Column('levels_completed', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('current_level', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('assigned', 'in_progress', 'completed', 'failed', name='trainingstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'assignment_id', 'week_start_date', name='uq_user_assignment_week')
    )
    op.create_index(op.f('ix_training_progress_id'), 'training_progress', ['id'], unique=False)
    op.create_table('mcq_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.Enum('A', 'B', 'C', 'D', name='mcq_option'), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_obtained', sa.Float(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exam_attempt_id'], ['mcq_exam_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['mcq_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcq_answers_id'), 'mcq_answers', ['id'], unique=False)
    op.drop_index(op.f('ix_assignment_evaluations_id'), table_name='assignment_evaluations')
    op.drop_table('assignment_evaluations')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.add_column('assignments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('assignments', sa.Column('current_level_id', sa.Integer(), nullable=False))
    op.add_column('assignments', sa.Column('actual_completion_date', sa.DateTime(), nullable=True))
    op.add_column('assignments', sa.Column('assigned_by', sa.Integer(), nullable=False))
    op.add_column('assignments', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('assignments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('assignments', 'training_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('assignments_employee_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'training_levels', ['current_level_id'], ['id'])
    op.create_foreign_key(None, 'assignments', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key(None, 'assignments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'assignments', 'users', ['updated_by'], ['id'])
    op.drop_column('assignments', 'employee_id')
    op.add_column('trainings', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('trainings', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('trainings', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('trainings', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('trainings', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'trainings', ['title'])
    op.create_foreign_key(None, 'trainings', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'trainings', 'users', ['updated_by'], ['id'])
    op.drop_column('trainings', 'duration_hours')
    op.add_column('users', sa.Column('position', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'user_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'user_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'position')
    op.add_column('trainings', sa.Column('duration_hours', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.drop_constraint(None, 'trainings', type_='foreignkey')
    op.drop_constraint(None, 'trainings', type_='unique')
    op.alter_column('trainings', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('trainings', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('trainings', 'updated_at')
    op.drop_column('trainings', 'updated_by')
    op.drop_column('trainings', 'created_by')
    op.add_column('assignments', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_employee_id_fkey'), 'assignments', 'employees', ['employee_id'], ['id'])
    op.alter_column('assignments', 'training_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('assignments', 'created_at')
    op.drop_column('assignments', 'updated_by')
    op.drop_column('assignments', 'assigned_by')
    op.drop_column('assignments', 'actual_completion_date')
    op.drop_column('assignments', 'current_level_id')
    op.drop_column('assignments', 'user_id')
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('employees_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('employee_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('designation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employees_pkey'),
    sa.UniqueConstraint('employee_code', name='employees_employee_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_table('assignment_evaluations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level', postgresql.ENUM('basic', 'intermediate', 'advanced', name='traininglevel'), autoincrement=False, nullable=False),
    sa.Column('evaluation_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('evaluation_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('evaluation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('mcq_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('assignment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('assignment_evaluations_assignment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assignment_evaluations_pkey')),
    sa.UniqueConstraint('assignment_id', 'level', name=op.f('uq_assignment_level'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_assignment_evaluations_id'), 'assignment_evaluations', ['id'], unique=False)
    op.drop_index(op.f('ix_mcq_answers_id'), table_name='mcq_answers')
    op.drop_table('mcq_answers')
    op.drop_index(op.f('ix_training_progress_id'), table_name='training_progress')
    op.drop_table('training_progress')
    op.drop_index(op.f('ix_mcq_exam_attempts_id'), table_name='mcq_exam_attempts')
    op.drop_table('mcq_exam_attempts')
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_mcq_questions_id'), table_name='mcq_questions')
    op.drop_table('mcq_questions')
    op.drop_index(op.f('ix_training_levels_id'), table_name='training_levels')
    op.drop_table('training_levels')
    # ### end Alembic commands ###
